<?php
/**
 * An Jia AI Description Generator
 * 
 * Handles the integration with DeepSeek AI for property descriptions
 */

if (!defined('ABSPATH')) {
    die('Direct access not allowed');
}

// Register the AI description field
function anjia_register_ai_description_field() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_ai_description',
        'title' => 'AI Generated Description',
        'fields' => array(
            array(
                'key' => 'field_ai_description',
                'label' => 'AI Generated Description',
                'name' => 'ai_description',
                'type' => 'textarea',
                'instructions' => 'This description is automatically generated by AI based on property details.',
                'required' => 0,
                'readonly' => 1,
            ),
            array(
                'key' => 'field_regenerate_description',
                'label' => 'Regenerate Description',
                'name' => 'regenerate_description',
                'type' => 'true_false',
                'instructions' => 'Toggle this to regenerate the AI description',
                'default_value' => 0,
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'property',
                ),
            ),
        ),
        'position' => 'normal',
        'style' => 'default',
    ));
}
add_action('acf/init', 'anjia_register_ai_description_field');

// Generate description using DeepSeek AI
function anjia_generate_ai_description($property_id) {
    // Get property details
    $title = get_the_title($property_id);
    $type = get_field('property_type', $property_id);
    $amenities = get_field('amenities', $property_id);
    $price = get_field('price', $property_id);
    $bedrooms = get_field('bedrooms', $property_id);
    $bathrooms = get_field('bathrooms', $property_id);
    $size = get_field('size', $property_id);
    $neighborhood = wp_get_post_terms($property_id, 'neighborhood', array('fields' => 'names'));
    $neighborhood = !empty($neighborhood) ? $neighborhood[0] : '';

    // Prepare property features for AI prompt
    $features = array(
        "Type: $type",
        "Price: $price",
        "Size: $size sq ft",
        "Location: $neighborhood",
    );

    if ($bedrooms) $features[] = "$bedrooms bedrooms";
    if ($bathrooms) $features[] = "$bathrooms bathrooms";
    if ($amenities && is_array($amenities)) {
        foreach ($amenities as $amenity) {
            $features[] = anjia_get_amenities_choices()[$amenity];
        }
    }

    // Prepare API request
    $api_key = defined('DEEPSEEK_API_KEY') ? DEEPSEEK_API_KEY : '';
    if (empty($api_key)) {
        error_log('DeepSeek API key not configured');
        return false;
    }

    $prompt = "Write a professional and engaging real estate property description for the following property:\n\n";
    $prompt .= "Property: $title\n";
    $prompt .= implode("\n", $features);
    $prompt .= "\n\nWrite approximately 200 words. Focus on the unique selling points and lifestyle benefits. Use natural, flowing language.";

    $response = wp_remote_post('https://api.deepseek.com/v1/chat/completions', array(
        'headers' => array(
            'Authorization' => "Bearer $api_key",
            'Content-Type' => 'application/json',
        ),
        'body' => json_encode(array(
            'model' => 'deepseek-chat',
            'messages' => array(
                array(
                    'role' => 'system',
                    'content' => 'You are a professional real estate copywriter.'
                ),
                array(
                    'role' => 'user',
                    'content' => $prompt
                )
            ),
            'temperature' => 0.7,
            'max_tokens' => 500
        ))
    ));

    if (is_wp_error($response)) {
        error_log('DeepSeek API Error: ' . $response->get_error_message());
        return false;
    }

    $body = json_decode(wp_remote_retrieve_body($response), true);
    if (isset($body['choices'][0]['message']['content'])) {
        return wp_kses_post($body['choices'][0]['message']['content']);
    }

    return false;
}

// Generate description when property is saved
function anjia_maybe_generate_description($post_id) {
    // Only run for property post type
    if (get_post_type($post_id) !== 'property') {
        return;
    }

    // Check if we need to generate/regenerate
    $regenerate = get_field('regenerate_description', $post_id);
    $existing_description = get_field('ai_description', $post_id);

    if ($regenerate || empty($existing_description)) {
        $description = anjia_generate_ai_description($post_id);
        if ($description) {
            update_field('ai_description', $description, $post_id);
            update_field('regenerate_description', 0, $post_id);
        }
    }
}
add_action('acf/save_post', 'anjia_maybe_generate_description', 20);

// Add the AI description to the REST API response
function anjia_add_ai_description_to_api() {
    register_rest_field('property', 'ai_description', array(
        'get_callback' => function($object) {
            return get_field('ai_description', $object['id']);
        },
        'schema' => array(
            'description' => 'AI Generated property description',
            'type' => 'string',
        ),
    ));
}
add_action('rest_api_init', 'anjia_add_ai_description_to_api');
